### ISSUE TITLE
Make infinite loop work when the stack is empty.

### ISSUE THREAD

**Issue by William8915** [tomtheisen/stax#2] opened 2018-02-11 12:35 UTC
Ideally, a no-op infinite loop should be achieved by a single letter `W`. However, this does not work in the current version of Stax and gives a error about trying to pop an empty stack.

**Comment by tomtheisen** [comment] 2018-02-11 16:12
Confirmed. That's a bug.

**Comment by tomtheisen** [comment] 2018-02-11 16:37
Fixed in commit 51a7b173430ff3dd299abef8858f1f011af111ea.  Is there a way to formally link it?  I haven't used github issues before.

**Comment by tomtheisen** [comment] 2018-02-11 16:37
Oh, it turned it into a hyper link.  Nice.

**Closed by tomtheisen** 2018-02-11 16:37 UTC
Labels: bug

**Comment by tomtheisen** [comment] 2018-02-11 17:57
More robustly fixed in 363fe83809b8f0f5c0c168d71a4a849a83d1e6a5.  Since this a change to the language behavior, I bumped the version to 1.0.1.  I don't think it's a breaking change, because all existing working programs should have the same behavior.

**Comment by William8915** [comment] 2018-02-11 23:10
That's good. I agree that there should be a general fix.
